version: "3"
services:
  face-recognition:
    build: .
    ports:
      - 5001:5001
    environment:
      APP_CONFIG: config/prod.cfg
    volumes:
      - ./logs:/var/log/face-recognition/
    command: sh ./entrypoint.sh
